import os
import json
import urllib.request
import urllib.error
import time
try:
    from .config import GEMINI_MODEL, GEMINI_API_KEY, SYSTEM_PROMPT, BASE_DIR
    from .static_analyzer import run_static_checks, analyze_code_metrics
except ImportError:
    from config import GEMINI_MODEL, GEMINI_API_KEY, SYSTEM_PROMPT, BASE_DIR
    from static_analyzer import run_static_checks, analyze_code_metrics

def get_effective_api_key(api_key: str = None) -> str:
    """Resolve API key from parameter, environment, or dynamically from .env file."""
    if api_key and api_key.strip():
        return api_key.strip()
    env_val = os.environ.get("GEMINI_API_KEY", "").strip()
    if env_val:
        return env_val
    if GEMINI_API_KEY and GEMINI_API_KEY.strip():
        return GEMINI_API_KEY.strip()
    # Check .env file dynamically without requiring server restart
    env_file = BASE_DIR / ".env"
    if env_file.is_file():
        try:
            with open(env_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        k, v = line.split("=", 1)
                        if k.strip() == "GEMINI_API_KEY":
                            val = v.strip().strip("'\"")
                            if val:
                                os.environ["GEMINI_API_KEY"] = val
                                return val
        except Exception:
            pass
    return ""

def call_gemini_api(code: str, language: str, api_key: str, model: str = None) -> dict:
    preferred_model = model or GEMINI_MODEL
    models_to_try = [preferred_model]
    for fallback in ["gemini-3.6-flash", "gemini-flash-latest", "gemini-3.5-flash", "gemini-2.0-flash", "gemini-1.5-flash"]:
        if fallback not in models_to_try:
            models_to_try.append(fallback)

    user_prompt = f"""Review the following {language} code. Provide a complete, rigorous code review adhering strictly to the JSON schema.

Source Code:
```{language}
{code}
```
"""

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": SYSTEM_PROMPT},
                    {"text": user_prompt}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    }
    req_data = json.dumps(payload).encode("utf-8")

    last_error = None
    for active_model in models_to_try:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{active_model}:generateContent?key={api_key}"
        req = urllib.request.Request(
            url,
            data=req_data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        
        try:
            with urllib.request.urlopen(req, timeout=45) as response:
                res_body = response.read().decode("utf-8")
                res_json = json.loads(res_body)
                
                candidates = res_json.get("candidates", [])
                if not candidates:
                    raise ValueError("No response generated by AI model.")
                
                parts = candidates[0].get("content", {}).get("parts", [])
                if not parts:
                    raise ValueError("Empty response parts from AI model.")
                    
                text = parts[0].get("text", "").strip()
                if text.startswith("```json"):
                    text = text[7:]
                if text.startswith("```"):
                    text = text[3:]
                if text.endswith("```"):
                    text = text[:-3]
                
                parsed_review = json.loads(text.strip())
                parsed_review["source"] = "gemini_ai"
                parsed_review["model_used"] = active_model
                return parsed_review
                
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8") if e.fp else str(e)
            if e.code == 404:
                last_error = f"Model {active_model} not found (HTTP 404): {err_msg}"
                continue
            raise RuntimeError(f"Gemini API Error (HTTP {e.code}): {err_msg}")
        except urllib.error.URLError as e:
            raise RuntimeError(f"Network error connecting to Gemini API: {e.reason}")
        except json.JSONDecodeError as e:
            raise RuntimeError(f"Failed to parse JSON from AI model response: {str(e)}")

    raise RuntimeError(last_error or "Failed to connect to any Gemini models.")

def generate_heuristic_review(code: str, language: str, static_issues: list, metrics: dict) -> dict:
    """Intelligent fallback reviewer when no API key is provided or offline."""
    issues = list(static_issues)
    lines = code.splitlines()
    
    # Analyze common patterns for heuristic issues
    if language.lower() in ("python", "py"):
        if "import os" in code and "os.system" in code:
            issues.append({
                "id": f"heur-{len(issues)+1}",
                "line_start": 1,
                "line_end": len(lines),
                "category": "security",
                "severity": "critical",
                "title": "Unsafe os.system Usage",
                "description": "os.system passes strings directly to the system shell. Use subprocess.run with argument vectors instead.",
                "impact": "Vulnerable to arbitrary command injection if unsanitized parameters are used.",
                "suggestion": "Replace os.system with subprocess.run(['command', arg], check=True).",
                "original_code": "os.system(...)",
                "fixed_code": "subprocess.run([...], check=True)"
            })
            
        if "print(" in code and not any("logging" in line for line in lines):
            issues.append({
                "id": f"heur-{len(issues)+1}",
                "line_start": 1,
                "line_end": min(5, len(lines)),
                "category": "maintainability",
                "severity": "low",
                "title": "Use of Standard print() for Logging",
                "description": "Code relies on print() statements instead of a structured logging framework.",
                "impact": "Difficult to filter logs by severity or redirect logs in production environments.",
                "suggestion": "Configure and use Python's built-in 'logging' module.",
                "original_code": "print(...)",
                "fixed_code": "import logging\nlogger = logging.getLogger(__name__)\nlogger.info(...)"
            })

    elif language.lower() in ("javascript", "typescript", "js", "ts"):
        if "var " in code:
            issues.append({
                "id": f"heur-{len(issues)+1}",
                "line_start": 1,
                "line_end": len(lines),
                "category": "maintainability",
                "severity": "medium",
                "title": "Legacy 'var' Declaration",
                "description": "Code uses 'var' which has function scope and hoisting quirks.",
                "impact": "Can lead to variable leakage and unintended shadowing.",
                "suggestion": "Use 'const' for immutable bindings and 'let' for reassignable variables.",
                "original_code": "var item = ...",
                "fixed_code": "const item = ..."
            })

    # Calculate scores based on issue counts & metrics
    crit_count = sum(1 for i in issues if i.get("severity") == "critical")
    high_count = sum(1 for i in issues if i.get("severity") == "high")
    med_count = sum(1 for i in issues if i.get("severity") == "medium")
    low_count = sum(1 for i in issues if i.get("severity") == "low")
    
    penalty = (crit_count * 25) + (high_count * 15) + (med_count * 8) + (low_count * 3)
    base_score = max(20, min(100, 100 - penalty))
    
    if base_score >= 90:
        grade = "A"
    elif base_score >= 80:
        grade = "B"
    elif base_score >= 70:
        grade = "C"
    elif base_score >= 60:
        grade = "D"
    else:
        grade = "F"
        
    security_score = max(10, min(100, 100 - (crit_count * 35 + high_count * 20)))
    performance_score = max(30, min(100, 100 - (med_count * 15)))
    maintainability_score = metrics.get("maintainability_index", 75)
    
    # Generate improved code mockup
    improved_code = code
    for iss in issues:
        orig = iss.get("original_code")
        fix = iss.get("fixed_code")
        if orig and fix and orig in improved_code and not fix.startswith("#"):
            improved_code = improved_code.replace(orig, fix, 1)

    summary = f"Code analyzed using built-in AST & Static Security Engine. Found {len(issues)} issue(s) across security, performance, and code quality. Overall health score is {base_score}/100 (Grade {grade})."
    if not issues:
        summary = "Code passed all static analysis checks with no major vulnerabilities or anti-patterns detected."
        
    test_cases = [
        {
            "name": f"test_{language.lower()}_edge_cases",
            "description": "Validates boundary conditions, null inputs, and error handling paths.",
            "code": f"# Unit test verification suite for {language}\\n# Test boundary conditions and error handlers"
        }
    ]

    return {
        "source": "heuristic_engine",
        "summary": summary,
        "score": base_score,
        "grade": grade,
        "metrics": {
            "security_score": security_score,
            "performance_score": performance_score,
            "maintainability_score": maintainability_score,
            "cyclomatic_complexity": metrics.get("cyclomatic_complexity", 1),
            "total_lines": metrics.get("total_lines", len(lines)),
            "complexity_rating": metrics.get("complexity_rating", "Low")
        },
        "issues": issues,
        "improved_code": improved_code,
        "test_cases": test_cases
    }

def review_code(code: str, language: str = "python", api_key: str = None, model: str = None) -> dict:
    """Main entry point to perform multi-stage code review."""
    start_time = time.time()
    
    # 1. Run local static analysis & metrics
    metrics = analyze_code_metrics(code, language)
    static_issues = run_static_checks(code, language)
    
    effective_api_key = get_effective_api_key(api_key)
    
    # 2. Try Gemini API if API key is provided
    if effective_api_key:
        try:
            ai_result = call_gemini_api(code, language, effective_api_key, model)
            # Merge static issues if not already reported
            combined_issues = list(ai_result.get("issues", []))
            existing_lines = {i.get("line_start") for i in combined_issues}
            for si in static_issues:
                if si.get("line_start") not in existing_lines:
                    combined_issues.append(si)
                    
            ai_result["issues"] = combined_issues
            # Add computed metrics
            ai_metrics = ai_result.get("metrics", {})
            ai_metrics.update({
                "cyclomatic_complexity": metrics.get("cyclomatic_complexity"),
                "total_lines": metrics.get("total_lines"),
                "complexity_rating": metrics.get("complexity_rating")
            })
            ai_result["metrics"] = ai_metrics
            ai_result["duration_sec"] = round(time.time() - start_time, 2)
            return ai_result
        except Exception as e:
            # If AI fails (e.g. invalid key or network timeout), fall back gracefully to heuristic engine
            result = generate_heuristic_review(code, language, static_issues, metrics)
            result["warning"] = f"AI Review fallback: {str(e)}"
            result["duration_sec"] = round(time.time() - start_time, 2)
            return result
    else:
        # Fallback to rich built-in engine
        result = generate_heuristic_review(code, language, static_issues, metrics)
        result["duration_sec"] = round(time.time() - start_time, 2)
        return result
